# site settings
title: Ziqi
subtitle: '@Dartmouth College'
email: strand314177@gmail.com
description: This is my personal website powered by Jekyll and hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ziqi
street_address: Dartmouth College 
city: Hanover
state: New Hampshire
country: United State

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/CyberStrand
  Linkedin: https://www.linkedin.com/in/ziqi-tian-229075308/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
